wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1689454560.588369
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 7
      - 23
      - 51
      4: 3.8.16
      5: 0.15.5
      8:
      - 1
      - 2
      - 4
      - 5
    m:
    - 1: _timestamp
    - 1: usage/prompt_tokens
      5: 1
      6:
      - 1
      - 3
    - 1: usage/total_tokens
      5: 1
      6:
      - 1
      - 3
    - 1: usage/completion_tokens
      5: 1
      6:
      - 1
      - 3
    - 1: usage/elapsed_time
      5: 1
      6:
      - 1
      - 3
