wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1689464356.761894
    t:
      1:
      - 5
      - 53
      - 55
      - 86
      - 92
      - 95
      2:
      - 5
      - 53
      - 55
      - 86
      - 92
      - 95
      3:
      - 2
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 1
      - 2
      - 4
      - 5
      9:
        2: langchain
