wandb_version: 1

faiss_artifact:
  desc: null
  value: parambharat/wandb_docs_bot/faiss_store:latest
hyde_prompt_artifact:
  desc: null
  value: parambharat/wandb_docs_bot/hyde_prompt:latest
chat_prompt_artifact:
  desc: null
  value: parambharat/wandb_docs_bot/system_prompt:latest
model_name:
  desc: null
  value: gpt-4
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1689540686.444691
    t:
      1:
      - 55
      - 86
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 2
      - 5
