wandb_version: 1

project:
  desc: null
  value: llmapps
entity:
  desc: null
  value: null
job_type:
  desc: null
  value: production
vector_store_artifact:
  desc: null
  value: darek/llmapps/vector_store:latest
chat_prompt_artifact:
  desc: null
  value: darek/llmapps/chat_prompt:latest
chat_temperature:
  desc: null
  value: 0.3
max_fallback_retries:
  desc: null
  value: 1
model_name:
  desc: null
  value: gpt-3.5-turbo
eval_model:
  desc: null
  value: gpt-3.5-turbo
eval_artifact:
  desc: null
  value: darek/llmapps/generated_examples:v0
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1689541544.37794
    t:
      1:
      - 55
      - 86
      2:
      - 55
      - 86
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 2
      - 4
      - 5
